test:
  queue_host:  'localhost'
  elastic_host:  '10.1.3.16'
  tcas_host:  'localhost:10000'

development:
  queue_host:  'localhost'
  elastic_host:  '10.1.3.16'
  tcas_host:  'localhost:10000'

staging:
   queue_host:  '10.0.3.1'
   elastic_host:  'localhost'
   tcas_host:  '10.0.3.1'

production:
   queue_host:  '10.0.3.1'
   elastic_host:  'localhost'
   tcas_host:  'localhost'


